covidstat:
    image: alparslanabdikoglu/covidapp
    restart: unless-stopped
    labels:
      - "traefik.http.routers.covidstat.rule=Host(`koronainfok.com`)"
      - "traefik.http.routers.covidstat.middlewares=covidstat-ssl"

      - "traefik.http.middlewares.covidstat-ssl.redirectscheme.scheme=https"
      - "traefik.http.middlewares.covidstat-ssl.redirectscheme.permanent=true"

      - "traefik.http.routers.covidstat-ssl.rule=Host(`koronainfok.com`)"
      - "traefik.http.routers.covidstat-ssl.tls=true"
      - "traefik.http.routers.covidstat-ssl.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.covidstat-ssl.tls.domains[0].main=koronainfok.com"
